import React, { createContext, useContext, useState, useEffect } from 'react'
import { trackLanguageSwitch } from './analytics'

type Language = 'en' | 'ru'

interface LanguageContextType {
    lang: Language
    setLang: (lang: Language) => void
    t: (key: string) => string
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined)

export const useLanguage = () => {
    const context = useContext(LanguageContext)
    if (!context) throw new Error('useLanguage must be used within LanguageProvider')
    return context
}

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
    const [lang, setLangState] = useState<Language>(() => {
        const saved = localStorage.getItem('wtp-lang')
        return (saved === 'ru' || saved === 'en') ? saved : 'en'
    })

    const setLang = (newLang: Language) => {
        setLangState(newLang)
        localStorage.setItem('wtp-lang', newLang)
        trackLanguageSwitch(newLang)
    }

    useEffect(() => {
        document.documentElement.lang = lang
    }, [lang])

    const t = (key: string): string => {
        const translation = translations[lang]?.[key]
        if (!translation) {
            // Fallback to English, then to key itself
            return translations['en']?.[key] || key
        }
        return translation
    }

    return (
        <LanguageContext.Provider value={{ lang, setLang, t }}>
            {children}
        </LanguageContext.Provider>
    )
}

// ---- Translations ----

const translations: Record<string, Record<string, string>> = {
    en: {
        // Navbar
        'nav.process': 'Process',
        'nav.partners': 'Partners',
        'nav.risk': 'Risk',
        'nav.contact': 'Contact',

        // Hero
        'hero.label': 'For Brokers & Advisors',
        'hero.title': 'A reliable UAE execution partner built for bankability and compliance.',
        'hero.subtitle': 'WTP is an on-the-ground operator taking clients from intent to outcome safely, without reputational risk.',
        'hero.cta.kit': 'Get the Partner Kit',
        'hero.cta.case': 'Submit a Case',

        // Who it's for
        'who.label': 'Who it\'s for',
        'who.title': 'Partners who need on-site quality control.',
        'who.text': 'You have clients, but lack strong local execution. Designed for brokers, private bankers, advisors, family offices, lawyers, and agencies outside the UAE.',

        // Partner Benefits
        'benefits.label': 'Partner Benefits',
        'benefits.ownership.title': 'Ownership Protection',
        'benefits.ownership.text': 'We never bypass the partner, and we don\'t sell directly around you. Your client relationships remain yours.',
        'benefits.transparency.title': 'Transparency',
        'benefits.transparency.text': 'Clear status updates, scope and change control, and defined checkpoints throughout the process.',
        'benefits.control.title': 'Control',
        'benefits.control.text': 'Decisions are made upfront: whether we can proceed, and under exactly what conditions.',
        'benefits.quality.title': 'Quality',
        'benefits.quality.text': 'Optimized for banks and regulators, not "speed at any cost." We prioritize long-term stability.',

        // Process
        'process.label': 'Delivery Process',
        'process.title': 'How we work',
        'process.terms': 'See full terms →',
        'process.step1.title': 'Pre-screen',
        'process.step1.desc': 'Documents, KYC/AML, Source of Funds, and risk map before any action.',
        'process.step2.title': 'Banking Scenario',
        'process.step2.desc': 'Bank routing and requirements selection. No "guaranteed account" promises.',
        'process.step3.title': 'Delivery',
        'process.step3.desc': 'Company setup, accounts, visas, and operations support within agreed scenario.',
        'process.step4.title': 'Ongoing',
        'process.step4.desc': 'Retainer support to ensure stability and maximize LTV.',

        // Engagement
        'engagement.label': 'Engagement Models',
        'engagement.referral.title': 'Referral',
        'engagement.referral.text': 'The client knows WTP. The partner is paid a commission under agreed rules.',
        'engagement.whitelabel.title': 'White-label',
        'engagement.whitelabel.text': 'The client may not know WTP. We work as a subcontractor; all communication goes through the partner.',
        'engagement.protection.title': 'Partner Protection Policy',
        'engagement.protection.crm': 'Client assigned to partner in CRM registry',
        'engagement.protection.contact': 'Direct contact only in agreed format',
        'engagement.protection.terms': 'Terms don\'t change without approval',
        'engagement.protection.commission': 'Commissions agreed upfront',

        // Risk
        'risk.label': 'Risk Policy',
        'risk.green.status': 'We Accept',
        'risk.green.desc': 'Transparent business rationale, document readiness, no critical red flags, realistic expectations.',
        'risk.yellow.status': 'Accept w/ Conditions',
        'risk.yellow.desc': 'Higher risk, complex structure, non-standard operations. Requires enhanced control, fixed scope, separate pricing, written risk acknowledgment.',
        'risk.red.status': 'We Decline',
        'risk.red.desc': 'Sanctions/toxic exposure, missing documents, "do it with no questions asked" requests, pressure to break rules.',

        // Products
        'products.label': 'Product Line',
        'products.subtitle': 'End-to-end services designed for the discerning partner and their clients.',
        'products.banking.pill': 'Core Service',
        'products.banking.title': 'Corporate Banking',
        'products.banking.desc': 'Corporate account opening, payment infrastructure, and ongoing compliance support. We navigate the bank\'s requirements so you don\'t have to.',
        'products.banking.cta': 'View Details',
        'products.premium.pill': 'Personal',
        'products.premium.title': 'Premium Banking',
        'products.premium.desc': 'Personal accounts, private banking introductions, and investment access for HNW individuals relocating to the UAE.',
        'products.premium.cta': 'View Details',
        'products.business.pill': 'Operations',
        'products.business.title': 'Company Formation',
        'products.business.desc': 'Free zone and mainland registration, trade licensing, and corporate structuring — all designed around banking acceptance.',
        'products.business.cta': 'View Details',
        'products.residency.pill': 'Identity',
        'products.residency.title': 'Visa & Residency',
        'products.residency.desc': 'Employment visas, investor visas, Golden Visa, Emirates ID — integrated with tax logic and banking requirements.',
        'products.residency.cta': 'View Details',
        'products.tax.pill': 'Tax',
        'products.tax.title': 'Tax Residency',
        'products.tax.desc': 'Tax residency certificates, substance requirements, and double tax treaty planning for individuals and holding structures.',
        'products.tax.cta': 'View Details',
        'products.accounting.pill': 'Operations',
        'products.accounting.title': 'Accounting',
        'products.accounting.desc': 'Bookkeeping, VAT filing, corporate tax, audit preparation, and payroll — aligned with banking compliance from day one.',
        'products.accounting.cta': 'View Details',
        'products.realestate.pill': 'Investment',
        'products.realestate.title': 'Real Estate',
        'products.realestate.desc': 'Residential and commercial acquisition, Golden Visa qualifying properties, conveyancing, and title deed management.',
        'products.realestate.cta': 'View Details',
        'products.wealth.pill': 'Legacy',
        'products.wealth.title': 'Wealth & Protection',
        'products.wealth.desc': 'Wills, foundations, family office structuring, and private custody solutions for long-term asset protection.',
        'products.wealth.cta': 'View Details',

        // Engagement Page
        'engPage.back': '← Back to Overview',
        'engPage.label': 'PARTNERSHIP MODELS',
        'engPage.title': 'Referral or White-label — you choose.',
        'engPage.subtitle': 'Two models, one standard of execution. Both protect the partner relationship and ensure consistent delivery quality.',
        'engPage.referral.label': 'MODEL A',
        'engPage.referral.title': 'Referral',
        'engPage.referral.intro': 'The client knows about WTP. You introduce us, we deliver, you earn commission. Simple, transparent, accountable.',
        'engPage.referral.how': 'How it works',
        'engPage.referral.step1': 'You introduce the client to WTP with context on their needs',
        'engPage.referral.step2': 'We run pre-screen, confirm scope, and agree on pricing directly with the client',
        'engPage.referral.step3': 'You receive agreed commission upon case milestones',
        'engPage.referral.step4': 'Client relationship is locked to you in our CRM — no bypass, no exceptions',
        'engPage.referral.best': 'Best for',
        'engPage.referral.best1': 'Advisors who don\'t need to be involved in day-to-day execution',
        'engPage.referral.best2': 'Partners who want transparent, trackable cases',
        'engPage.referral.best3': 'Firms that prefer clients to know who handles UAE operations',
        'engPage.whitelabel.label': 'MODEL B',
        'engPage.whitelabel.title': 'White-label',
        'engPage.whitelabel.intro': 'The client may not know about WTP. We work behind the scenes as your execution team. All communication goes through you.',
        'engPage.whitelabel.how': 'How it works',
        'engPage.whitelabel.step1': 'You send us the case details and documents under your brand',
        'engPage.whitelabel.step2': 'We execute the full scope: registration, banking, visas, compliance',
        'engPage.whitelabel.step3': 'All client-facing communication is routed through you',
        'engPage.whitelabel.step4': 'Pricing is cost + fee — you control the margin',
        'engPage.whitelabel.best': 'Best for',
        'engPage.whitelabel.best1': 'Law firms and advisory boutiques with their own client-facing brand',
        'engPage.whitelabel.best2': 'Partners who want full control over the client relationship',
        'engPage.whitelabel.best3': 'Cases where discretion and branding matter',
        'engPage.protection.label': 'PARTNER PROTECTION',
        'engPage.protection.title': 'Non-negotiable guarantees',
        'engPage.protection.subtitle': 'These apply to both models — Referral and White-label.',
        'engPage.prot.crm': 'CRM Lock',
        'engPage.prot.crmDesc': 'Every client is assigned to the referring partner in our CRM. No bypass, no re-assignment without consent.',
        'engPage.prot.contact': 'Contact Rules',
        'engPage.prot.contactDesc': 'We only contact the client in the format agreed with the partner. No unsolicited calls, no side deals.',
        'engPage.prot.terms': 'Fixed Terms',
        'engPage.prot.termsDesc': 'Commercial terms are set upfront. No post-hoc changes to commissions, scope, or pricing without partner approval.',
        'engPage.prot.commission': 'Transparent Commissions',
        'engPage.prot.commissionDesc': 'Commission structure and payment triggers are agreed before the case starts. No hidden fees, no surprises.',

        // Risk Page
        'riskPage.back': '← Back to Overview',
        'riskPage.label': 'RISK CLASSIFICATION',
        'riskPage.title': 'We say no when it matters.',
        'riskPage.subtitle': 'Every case goes through a risk assessment before we commit. This protects the client, the partner, and us.',
        'riskPage.green.label': 'GREEN — WE ACCEPT',
        'riskPage.green.title': 'Standard Cases',
        'riskPage.green.intro': 'Transparent business logic, clean documentation, realistic expectations. The majority of cases fall here.',
        'riskPage.green.criteria': 'Acceptance criteria',
        'riskPage.green.c1': 'Clear source of funds with supporting documentation',
        'riskPage.green.c2': 'Legitimate business activity with verifiable track record',
        'riskPage.green.c3': 'No sanctions exposure or PEP status, or fully documented PEP',
        'riskPage.green.c4': 'Realistic expectations about timelines and banking outcomes',
        'riskPage.green.c5': 'Willingness to comply with KYC/AML requirements',
        'riskPage.yellow.label': 'YELLOW — ACCEPT WITH CONDITIONS',
        'riskPage.yellow.title': 'Enhanced Due Diligence',
        'riskPage.yellow.intro': 'Higher complexity, elevated risk, or non-standard structure. We can proceed, but with additional controls and separate pricing.',
        'riskPage.yellow.criteria': 'What triggers Yellow',
        'riskPage.yellow.c1': 'Complex multi-jurisdictional structures',
        'riskPage.yellow.c2': 'Industries with elevated banking scrutiny (fintech, crypto-adjacent, commodities)',
        'riskPage.yellow.c3': 'Documented PEP status requiring enhanced controls',
        'riskPage.yellow.c4': 'Large transaction volumes requiring compliance justification',
        'riskPage.yellow.conditions': 'Conditions',
        'riskPage.yellow.cond1': 'Fixed scope with written boundaries',
        'riskPage.yellow.cond2': 'Separate pricing reflecting additional compliance work',
        'riskPage.yellow.cond3': 'Written risk acknowledgment from both partner and client',
        'riskPage.yellow.cond4': 'Enhanced monitoring throughout the engagement',
        'riskPage.red.label': 'RED — WE DECLINE',
        'riskPage.red.title': 'Non-Starters',
        'riskPage.red.intro': 'We walk away. No exceptions, no negotiations. Protecting our banking relationships and partner reputation is more important than any single case.',
        'riskPage.red.criteria': 'Automatic decline',
        'riskPage.red.c1': 'Sanctions-listed individuals or entities',
        'riskPage.red.c2': 'Missing or fabricated source of funds documentation',
        'riskPage.red.c3': '"Do it with no questions asked" attitude toward compliance',
        'riskPage.red.c4': 'High-risk industries: unlicensed crypto exchanges, offshore gambling, defense trade, shell company networks',
        'riskPage.red.c5': 'Pressure to bypass regulatory requirements or bank policies',
        'riskPage.red.c6': 'Concealment intent without legal structure',

        // Partners Page
        'partnersPage.back': '← Back to Overview',
        'partnersPage.label': 'FOR PARTNERS',
        'partnersPage.title': 'Built for partners who value control.',
        'partnersPage.subtitle': 'We don\'t compete with you. We don\'t bypass you. We execute what you bring — on your terms.',
        'partnersPage.who.label': 'WHO WE WORK WITH',
        'partnersPage.who.title': 'Our partner profile',
        'partnersPage.who1.title': 'Wealth Managers & Family Offices',
        'partnersPage.who1.desc': 'Clients relocating wealth and family to the UAE. Need banking, structures, and visa — executed by someone who understands compliance.',
        'partnersPage.who2.title': 'Immigration Advisors',
        'partnersPage.who2.desc': 'Handle residency planning but need a trusted operator on the ground for company formation, banking, and ongoing compliance.',
        'partnersPage.who3.title': 'Tax Advisors & Accountants',
        'partnersPage.who3.desc': 'Plan the tax structure from home jurisdiction. Need UAE execution that aligns with the advisory work — not contradicts it.',
        'partnersPage.who4.title': 'Law Firms & Boutique Practices',
        'partnersPage.who4.desc': 'Advise on corporate structuring and relocation. Need reliable, white-label execution without reputational risk.',
        'partnersPage.why.label': 'WHY PARTNERS CHOOSE US',
        'partnersPage.own.title': 'Ownership Protection',
        'partnersPage.own.desc': 'We never bypass the partner, and we don\'t sell directly around you. Your client relationships remain yours. Every client is locked to you in our CRM — no re-assignment without consent.',
        'partnersPage.trans.title': 'Transparency',
        'partnersPage.trans.desc': 'Clear status updates at every stage. Scope and change control documented. No hidden fees, no surprise pricing. You always know where the case stands.',
        'partnersPage.ctrl.title': 'Control',
        'partnersPage.ctrl.desc': 'Decisions are made upfront: whether we can proceed, and under exactly what conditions. No commitments without your knowledge. No scope changes without your approval.',
        'partnersPage.qual.title': 'Quality',
        'partnersPage.qual.desc': 'Optimized for banks and regulators, not "speed at any cost." We prioritize long-term stability. A structure that passes compliance today and survives audit tomorrow.',

        // CTA
        'cta.title': 'Start with a Pilot',
        'cta.text': 'Get a pre-screen verdict, a commercial offer with clear boundaries, and a delivery plan with control points.',
        'cta.kit': 'Request Partner Kit',
        'cta.case': 'Submit a Case',

        // Partner Kit
        'partnerKit.back': 'Back to Overview',
        'partnerKit.title': 'Partner Kit',
        'partnerKit.label': 'PARTNER DOCUMENTATION',
        'partnerKit.subtitle': 'Everything you need to understand how we work, evaluate fit, and present WTP to your clients.',
        'partnerKit.featured': 'Overview',
        'partnerKit.onepager.title': 'WTP One Pager',
        'partnerKit.onepager.desc': 'A concise overview of our partnership model, risk framework, and product lines. Ideal for sharing with involved stakeholders.',
        'partnerKit.download.btn': 'Download PDF',
        'partnerKit.docs': 'Documentation',
        'partnerKit.docsSubtitle': 'Detailed documents for you and your clients.',
        'partnerKit.process.title': 'Process Map',
        'partnerKit.process.desc': '10-stage banking-first delivery workflow. Understand what happens after you refer a client.',
        'partnerKit.risk.title': 'Risk Policy',
        'partnerKit.risk.desc': '3-tier client classification (Green / Yellow / Red). Know who to refer and who to skip.',
        'partnerKit.packages.title': 'Service Packages',
        'partnerKit.packages.desc': 'L0 to L3 — scope, pricing ranges, and what\'s included. Share with clients to set expectations.',
        'partnerKit.intake.title': 'Intake Checklist',
        'partnerKit.intake.desc': 'KYC Light — documents your client needs to prepare before submission.',
        'partnerKit.cta.title': 'Ready to start?',
        'partnerKit.cta.text': 'Submit your first case — we\'ll do a free pre-screen within 5-7 business days.',
        'partnerKit.cta.btn': 'Submit a Case',
        'partnerKit.backHome': 'Back to Home',

        // Submit Case
        'submitCase.label': 'Partner Portal',
        'submitCase.title': 'Submit a Case',
        'submitCase.subtitle': 'Start the pre-screen process. Please provide the following details about your client.',
        'submitCase.contact': 'Contact Information',
        'submitCase.name': 'Your Name',
        'submitCase.email': 'Email',
        'submitCase.telegram': 'Telegram',
        'submitCase.client': 'Client Details',
        'submitCase.nationality': 'Client Nationality',
        'submitCase.residency': 'Current Residency',
        'submitCase.activity': 'Business Activity',
        'submitCase.activityPlaceholder': 'Describe the client\'s business activity in detail...',
        'submitCase.banking': 'Banking & Compliance',
        'submitCase.jurisdiction': 'Preferred Banking Jurisdiction',
        'submitCase.funds': 'Source of Funds',
        'submitCase.fundsPlaceholder': 'Describe the origin of funds in detail...',
        'submitCase.success': 'Your case has been submitted successfully! We\'ll review it and get back to you within 24 hours.',
        'submitCase.error': 'Something went wrong. Please try again or contact us directly.',
        'submitCase.submitting': 'Submitting...',
        'submitCase.submit': 'Submit Case',
        'submitCase.backHome': 'Back to Home',

        // Footer
        'footer.tagline': 'UAE Execution Partner.',
        'footer.contact': 'Contact',
        'footer.legal': 'Legal',
        'footer.terms': 'Terms of Service',
        'footer.privacy': 'Privacy Policy',
        'footer.office': 'Office',
        'footer.address': 'Office 1207, Arenco Tower\nMedia City, Dubai, UAE',

        // Cookie Banner
        'cookie.text': 'We use cookies for analytics to improve our website. You can accept or reject non-essential cookies.',
        'cookie.learnMore': 'Learn more',
        'cookie.accept': 'Accept All',
        'cookie.reject': 'Reject All',
        'cookie.ariaLabel': 'Cookie consent',

        // Form Consent
        'form.consent.prefix': 'I agree to the processing of my personal data in accordance with the',
        'form.consent.link': 'Privacy Policy',

        // Accessibility
        'a11y.skipToContent': 'Skip to content',

        // Contact Page
        'contact.label': 'Get in Touch',
        'contact.title': 'Contact Us',
        'contact.subtitle': 'Get in touch with our team. We\'ll get back to you within 24 hours.',
        'contact.formTitle': 'Send us a message',
        'contact.name': 'Name',
        'contact.namePlaceholder': 'John Doe',
        'contact.email': 'Email',
        'contact.emailPlaceholder': 'john@example.com',
        'contact.telegram': 'Telegram',
        'contact.telegramPlaceholder': '@username',
        'contact.message': 'Message',
        'contact.messagePlaceholder': 'Tell us about your inquiry...',
        'contact.success': 'Your message has been sent successfully! We\'ll get back to you soon.',
        'contact.error': 'Something went wrong. Please try again or reach out via email directly.',
        'contact.submitting': 'Sending...',
        'contact.submit': 'Send Message',
        'contact.backHome': 'Back to Home',
        'contact.info': 'Get in Touch',
        'contact.emailLabel': 'Email',
        'contact.phoneLabel': 'Phone',
        'contact.officeLabel': 'Office',
        'contact.address': 'Office 1207, Arenco Tower\nMedia City, Dubai, UAE',
        'contact.responseTime': 'Response Time',
        'contact.responseText': 'We typically respond within 24 hours during business days. For urgent matters, please reach out via Telegram.',

        // Process Page UI
        'processPage.back': '\u2190 Back to Overview',
        'processPage.notFound': 'Process Step Not Found',
        'processPage.notFoundText': 'The requested process step does not exist.',
        'processPage.whatHappens': 'What Happens',
        'processPage.actions': 'Actions',
        'processPage.result': 'Result',
        'processPage.outcome': 'Outcome',
        'processPage.nextStep': 'Next Step',
        'processPage.continue': 'Continue \u2192',

        // Terms Page
        'terms.back': '\u2190 Back to Process',
        'terms.title': 'Delivery Terms',
        'terms.label': 'DELIVERY PROCESS',
        'terms.subtitle': 'Our delivery principles, risk framework, and operating rules that govern every engagement.',
        'terms.principles': 'Core Principles',
        'terms.foundation': 'Foundation',
        'terms.bankingFirst': 'Banking First',
        'terms.bankingFirstDesc': 'We assess every case through the bank\'s lens before any registration. Structure is chosen to serve the bank, not the other way around.',
        'terms.compliance': 'Compliance Over Speed',
        'terms.complianceDesc': 'We never cut corners. Quality of compliance documentation matters more than delivery speed.',
        'terms.scope': 'Scope Before Promises',
        'terms.scopeDesc': 'No scope \u2014 no promises. Services, timelines, and pricing are fixed before work begins.',
        'terms.written': 'Written Changes Only',
        'terms.writtenDesc': 'All scope changes, additional services, and modifications must be confirmed in writing.',
        'terms.riskTitle': 'Risk Verdict Framework',
        'terms.gatekeeping': 'Gatekeeping',
        'terms.accept': '\u2705 We Accept',
        'terms.accept1': 'Multi-service potential clients',
        'terms.accept2': 'Partners and repeat clients',
        'terms.accept3': 'Transparent business logic',
        'terms.accept4': 'Long-term orientation',
        'terms.conditions': '\u26A0 Conditions Apply',
        'terms.conditions1': 'Complex banking cases',
        'terms.conditions2': 'No guarantee of result',
        'terms.conditions3': 'Complex structures or jurisdictions',
        'terms.conditionsNote': '\u2192 Higher pricing, fixed scope, no result guarantee',
        'terms.decline': '\u274C We Decline',
        'terms.decline1': 'Sanctioned persons',
        'terms.decline2': '"Do it without documents" requests',
        'terms.decline3': 'No prepayment readiness',
        'terms.decline4': 'One-off tasks without continuation',
        'terms.decline5': 'Concierge requests outside partnership',
        'terms.neverTitle': 'What We Never Do',
        'terms.redLines': 'Red Lines',
        'terms.never1': 'Promise impossible outcomes',
        'terms.never2': 'Minimize or hide compliance risks',
        'terms.never3': 'Improvise in gray areas',
        'terms.never4': 'Bypass partner in client communication',
        'terms.never5': 'Share client data with third parties',
        'terms.never6': 'Make undocumented agreements',

        // Updates Page
        'updates.back': '\u2190 Back to Overview',
        'updates.title': 'Updates',
        'updates.label': 'CHANGELOG',
        'updates.subtitle': 'Latest updates on banking scenarios, regulatory changes, and new product capabilities.',
        'updates.empty': 'No updates yet.',
        'updates.backHome': 'Back to Home',

        // Product Page UI
        'product.back': '\u2190 Back to Overview',
        'product.notFound': 'Product Not Found',
        'product.notFoundText': 'The requested product line does not exist.',
        'product.services': 'Services',
        'product.scope': 'Scope',
        'product.redFlags': 'Red Flags',
        'product.attention': 'Attention',
        'product.result': 'Expected Result',
        'product.outcome': 'Outcome',

        // SubmitCase Placeholders
        'submitCase.namePlaceholder': 'John Doe',
        'submitCase.emailPlaceholder': 'john@example.com',
        'submitCase.telegramPlaceholder': '@username',
        'submitCase.nationalityPlaceholder': 'Select nationality',
        'submitCase.residencyPlaceholder': 'Select residency',
        'submitCase.jurisdictionPlaceholder': 'Select jurisdiction',

        // Privacy Policy Page
        'privacy.back': '← Back to Home',
        'privacy.title': 'Privacy Policy',
        'privacy.lastUpdated': 'Last updated: February 17, 2026',
        'privacy.controller.title': '1. Data Controller',
        'privacy.controller.text': 'The data controller is WELLCOME TO PARADISE REAL ESTATE BROKERS LLC, Office 1207, Arenco Tower, Media City, Dubai, UAE. For any questions regarding your personal data, please contact us at hello@wtpbrokers.com or call +971 600 575-294.',
        'privacy.dataCollected.title': '2. Data We Collect',
        'privacy.dataCollected.formsIntro': 'Through our forms we may collect the following personal data:',
        'privacy.dataCollected.name': 'Full name',
        'privacy.dataCollected.email': 'Email address',
        'privacy.dataCollected.telegram': 'Telegram handle',
        'privacy.dataCollected.nationality': 'Client nationality',
        'privacy.dataCollected.residency': 'Current residency',
        'privacy.dataCollected.business': 'Business activity description',
        'privacy.dataCollected.banking': 'Preferred banking jurisdiction',
        'privacy.dataCollected.funds': 'Source of funds description',
        'privacy.dataCollected.autoIntro': 'With your consent, we automatically collect:',
        'privacy.dataCollected.ip': 'IP address (anonymized)',
        'privacy.dataCollected.browser': 'Browser type and version',
        'privacy.dataCollected.pages': 'Pages visited and interaction data',
        'privacy.purpose.title': '3. Purpose of Processing',
        'privacy.purpose.crm': 'Processing and managing client inquiries via our CRM system',
        'privacy.purpose.communication': 'Communicating with you regarding your inquiry',
        'privacy.purpose.analytics': 'Website analytics to improve user experience (with consent)',
        'privacy.purpose.legal': 'Compliance with legal obligations',
        'privacy.legalBasis.title': '4. Legal Basis',
        'privacy.legalBasis.consent': 'Consent — for form submissions and analytics cookies (GDPR Art. 6(1)(a), UAE PDPL)',
        'privacy.legalBasis.contract': 'Performance of a contract — for processing your case inquiry',
        'privacy.legalBasis.legitimate': 'Legitimate interest — for website security and performance',
        'privacy.thirdParties.title': '5. Third-Party Data Processors',
        'privacy.thirdParties.bitrix': 'Bitrix24 — CRM system for managing client inquiries',
        'privacy.thirdParties.google': 'Google Analytics 4 — website analytics (only with your consent)',
        'privacy.thirdParties.hosting': 'GitHub Pages — website hosting',
        'privacy.thirdParties.note': 'We do not sell your personal data to any third parties. Data processors are bound by data processing agreements.',
        'privacy.retention.title': '6. Data Retention',
        'privacy.retention.text': 'We retain personal data submitted through our forms for up to 2 years from the date of your last interaction with us. Analytics data is retained for 14 months. You may request earlier deletion at any time.',
        'privacy.rights.title': '7. Your Rights',
        'privacy.rights.intro': 'Under GDPR, UAE PDPL, and DIFC Data Protection Law, you have the following rights:',
        'privacy.rights.access': 'Right of access — obtain a copy of your personal data',
        'privacy.rights.rectification': 'Right to rectification — correct inaccurate data',
        'privacy.rights.erasure': 'Right to erasure — request deletion of your data',
        'privacy.rights.restriction': 'Right to restriction — limit processing of your data',
        'privacy.rights.portability': 'Right to data portability — receive your data in a structured format',
        'privacy.rights.objection': 'Right to object — object to processing based on legitimate interest',
        'privacy.rights.withdraw': 'Right to withdraw consent — withdraw consent at any time without affecting prior processing',
        'privacy.rights.contact': 'To exercise any of these rights, please contact us at hello@wtpbrokers.com or call +971 600 575-294. We will respond within 30 days.',
        'privacy.cookies.title': '8. Cookies',
        'privacy.cookies.text': 'We use cookies only with your explicit consent. The following cookies may be set:',
        'privacy.cookies.ga': '_ga, _ga_* — Google Analytics cookies for understanding website usage (analytics category)',
        'privacy.cookies.session': 'wtp-cookie-consent — stores your cookie preference (strictly necessary, no consent required)',
        'privacy.cookies.control': 'You can manage your cookie preferences at any time by clearing your browser cookies and revisiting the site. The cookie consent banner will reappear.',
        'privacy.changes.title': '9. Changes to This Policy',
        'privacy.changes.text': 'We may update this Privacy Policy from time to time. The "last updated" date at the top reflects the most recent revision. We encourage you to review this page periodically.',
        'privacy.contact.title': '10. Contact Us',
        'privacy.contact.text': 'If you have questions about this Privacy Policy or wish to exercise your data rights, please contact us at hello@wtpbrokers.com, call +971 600 575-294, or visit wtpbrokers.com.',
    },
    ru: {
        // Navbar
        'nav.process': 'Процесс',
        'nav.partners': 'Партнёрам',
        'nav.risk': 'Риски',
        'nav.contact': 'Контакт',

        // Hero
        'hero.label': 'Для брокеров и консультантов',
        'hero.title': 'Надёжный execution-партнёр в ОАЭ, построенный вокруг банков и комплаенса.',
        'hero.subtitle': 'WTP — оператор на земле, который проводит клиента от намерения до результата безопасно и без репутационных рисков.',
        'hero.cta.kit': 'Получить Partner Kit',
        'hero.cta.case': 'Отправить кейс',

        // Who it's for
        'who.label': 'Для кого',
        'who.title': 'Партнёры, которым нужен контроль качества на месте.',
        'who.text': 'У вас есть клиенты, но нет сильного локального исполнителя. Для брокеров, частных банкиров, консультантов, семейных офисов, юристов и агентств за пределами ОАЭ.',

        // Partner Benefits
        'benefits.label': 'Преимущества для партнёра',
        'benefits.ownership.title': 'Защита клиента',
        'benefits.ownership.text': 'Мы никогда не обходим партнёра и не продаём напрямую мимо вас. Ваши клиентские отношения остаются вашими.',
        'benefits.transparency.title': 'Прозрачность',
        'benefits.transparency.text': 'Чёткие статусы, контроль объёма и изменений, определённые контрольные точки на каждом этапе.',
        'benefits.control.title': 'Контроль',
        'benefits.control.text': 'Решения принимаются заранее: можем ли мы двигаться дальше и на каких именно условиях.',
        'benefits.quality.title': 'Качество',
        'benefits.quality.text': 'Оптимизировано для банков и регуляторов, а не для «скорости любой ценой». Мы ставим на долгосрочную устойчивость.',

        // Process
        'process.label': 'Процесс работы',
        'process.title': 'Как мы работаем',
        'process.terms': 'Полные условия →',
        'process.step1.title': 'Pre-screen',
        'process.step1.desc': 'Документы, KYC/AML, источник средств и карта рисков до начала любых действий.',
        'process.step2.title': 'Банковский сценарий',
        'process.step2.desc': 'Выбор банков и требований. Без обещаний «гарантированного счёта».',
        'process.step3.title': 'Исполнение',
        'process.step3.desc': 'Регистрация, счета, визы и операционная поддержка в рамках согласованного сценария.',
        'process.step4.title': 'Сопровождение',
        'process.step4.desc': 'Ретейнер для обеспечения стабильности и максимизации LTV.',

        // Engagement
        'engagement.label': 'Модели сотрудничества',
        'engagement.referral.title': 'Referral',
        'engagement.referral.text': 'Клиент знает о WTP. Партнёр получает комиссию по согласованным правилам.',
        'engagement.whitelabel.title': 'White-label',
        'engagement.whitelabel.text': 'Клиент может не знать о WTP. Мы работаем как субподрядчик; коммуникация идёт через партнёра.',
        'engagement.protection.title': 'Политика защиты партнёра',
        'engagement.protection.crm': 'Клиент закреплён за партнёром в CRM',
        'engagement.protection.contact': 'Прямой контакт только в согласованном формате',
        'engagement.protection.terms': 'Условия не меняются без согласования',
        'engagement.protection.commission': 'Комиссии согласованы заранее',

        // Risk
        'risk.label': 'Риск-политика',
        'risk.green.status': 'Берём в работу',
        'risk.green.desc': 'Прозрачная бизнес-логика, готовность документов, отсутствие критичных red flags, реалистичные ожидания.',
        'risk.yellow.status': 'Берём с условиями',
        'risk.yellow.desc': 'Повышенный риск, сложная структура, нестандартные операции. Усиленный контроль, фиксированный объём, отдельное ценообразование, письменное подтверждение рисков.',
        'risk.red.status': 'Отказываем',
        'risk.red.desc': 'Санкции, токсичная экспозиция, отсутствие документов, запросы «сделайте без вопросов», давление с нарушением правил.',

        // Products
        'products.label': 'Продуктовая линейка',
        'products.subtitle': 'Специализированные услуги для требовательных партнёров и их клиентов.',
        'products.banking.pill': 'Ключевая услуга',
        'products.banking.title': 'Корпоративный банкинг',
        'products.banking.desc': 'Открытие корпоративных счетов, платёжная инфраструктура и сопровождение комплаенса. Мы ведём переговоры с банком за вас.',
        'products.banking.cta': 'Подробнее',
        'products.premium.pill': 'Персональный',
        'products.premium.title': 'Премиум-банкинг',
        'products.premium.desc': 'Персональные счета, private banking, инвестиционный доступ для HNW-клиентов, переезжающих в ОАЭ.',
        'products.premium.cta': 'Подробнее',
        'products.business.pill': 'Операции',
        'products.business.title': 'Регистрация компаний',
        'products.business.desc': 'Свободные зоны и mainland, торговые лицензии, корпоративное структурирование — всё под банковский acceptance.',
        'products.business.cta': 'Подробнее',
        'products.residency.pill': 'Идентичность',
        'products.residency.title': 'Визы и резидентство',
        'products.residency.desc': 'Рабочие визы, визы инвестора, Golden Visa, Emirates ID — интегрировано с налоговой логикой и банковскими требованиями.',
        'products.residency.cta': 'Подробнее',
        'products.tax.pill': 'Налоги',
        'products.tax.title': 'Налоговое резидентство',
        'products.tax.desc': 'Сертификаты налогового резидентства, substance requirements и планирование по соглашениям об избежании двойного налогообложения.',
        'products.tax.cta': 'Подробнее',
        'products.accounting.pill': 'Операции',
        'products.accounting.title': 'Бухгалтерия',
        'products.accounting.desc': 'Бухучёт, НДС, корпоративный налог, подготовка к аудиту и расчёт зарплат — в связке с банковским комплаенсом.',
        'products.accounting.cta': 'Подробнее',
        'products.realestate.pill': 'Инвестиции',
        'products.realestate.title': 'Недвижимость',
        'products.realestate.desc': 'Жилая и коммерческая недвижимость, объекты под Golden Visa, сопровождение сделок и управление правами собственности.',
        'products.realestate.cta': 'Подробнее',
        'products.wealth.pill': 'Наследие',
        'products.wealth.title': 'Активы и защита',
        'products.wealth.desc': 'Завещания, фонды, структурирование family office и кастоди-решения для долгосрочной защиты активов.',
        'products.wealth.cta': 'Подробнее',

        // Engagement Page
        'engPage.back': '← Назад к обзору',
        'engPage.label': 'МОДЕЛИ СОТРУДНИЧЕСТВА',
        'engPage.title': 'Referral или White-label — вы выбираете.',
        'engPage.subtitle': 'Две модели, один стандарт исполнения. Обе защищают партнёрские отношения и обеспечивают стабильное качество.',
        'engPage.referral.label': 'МОДЕЛЬ A',
        'engPage.referral.title': 'Referral',
        'engPage.referral.intro': 'Клиент знает о WTP. Вы представляете нас, мы исполняем, вы получаете комиссию. Просто, прозрачно, подотчётно.',
        'engPage.referral.how': 'Как это работает',
        'engPage.referral.step1': 'Вы представляете клиента WTP с контекстом о его потребностях',
        'engPage.referral.step2': 'Мы проводим pre-screen, подтверждаем объём и согласовываем цены напрямую с клиентом',
        'engPage.referral.step3': 'Вы получаете согласованную комиссию при достижении этапов кейса',
        'engPage.referral.step4': 'Клиент закреплён за вами в нашей CRM — без обхода, без исключений',
        'engPage.referral.best': 'Лучше всего подходит для',
        'engPage.referral.best1': 'Консультантов, которым не нужно участвовать в ежедневном исполнении',
        'engPage.referral.best2': 'Партнёров, которые хотят прозрачные, отслеживаемые кейсы',
        'engPage.referral.best3': 'Фирм, которые предпочитают, чтобы клиенты знали, кто ведёт операции в ОАЭ',
        'engPage.whitelabel.label': 'МОДЕЛЬ B',
        'engPage.whitelabel.title': 'White-label',
        'engPage.whitelabel.intro': 'Клиент может не знать о WTP. Мы работаем за кулисами как ваша команда исполнения. Вся коммуникация идёт через вас.',
        'engPage.whitelabel.how': 'Как это работает',
        'engPage.whitelabel.step1': 'Вы передаёте нам детали кейса и документы под вашим брендом',
        'engPage.whitelabel.step2': 'Мы исполняем полный объём: регистрация, банкинг, визы, комплаенс',
        'engPage.whitelabel.step3': 'Вся клиентская коммуникация проходит через вас',
        'engPage.whitelabel.step4': 'Ценообразование cost + fee — вы контролируете маржу',
        'engPage.whitelabel.best': 'Лучше всего подходит для',
        'engPage.whitelabel.best1': 'Юридических фирм и бутиковых практик с собственным клиентским брендом',
        'engPage.whitelabel.best2': 'Партнёров, которые хотят полный контроль над клиентскими отношениями',
        'engPage.whitelabel.best3': 'Кейсов, где важны дискретность и брендинг',
        'engPage.protection.label': 'ЗАЩИТА ПАРТНЁРА',
        'engPage.protection.title': 'Безусловные гарантии',
        'engPage.protection.subtitle': 'Действуют для обеих моделей — Referral и White-label.',
        'engPage.prot.crm': 'Фиксация в CRM',
        'engPage.prot.crmDesc': 'Каждый клиент закреплён за направившим партнёром в нашей CRM. Без обхода, без переназначения без согласия.',
        'engPage.prot.contact': 'Правила контакта',
        'engPage.prot.contactDesc': 'Мы связываемся с клиентом только в формате, согласованном с партнёром. Без несанкционированных звонков, без параллельных сделок.',
        'engPage.prot.terms': 'Фиксированные условия',
        'engPage.prot.termsDesc': 'Коммерческие условия устанавливаются заранее. Без постфактумных изменений комиссий, объёма или цен без согласования партнёра.',
        'engPage.prot.commission': 'Прозрачные комиссии',
        'engPage.prot.commissionDesc': 'Структура комиссий и триггеры выплат согласовываются до начала кейса. Без скрытых сборов, без сюрпризов.',

        // Risk Page
        'riskPage.back': '← Назад к обзору',
        'riskPage.label': 'КЛАССИФИКАЦИЯ РИСКОВ',
        'riskPage.title': 'Мы говорим «нет», когда это важно.',
        'riskPage.subtitle': 'Каждый кейс проходит оценку рисков до принятия обязательств. Это защищает клиента, партнёра и нас.',
        'riskPage.green.label': 'ЗЕЛЁНЫЙ — БЕРЁМ В РАБОТУ',
        'riskPage.green.title': 'Стандартные кейсы',
        'riskPage.green.intro': 'Прозрачная бизнес-логика, чистая документация, реалистичные ожидания. Большинство кейсов попадают сюда.',
        'riskPage.green.criteria': 'Критерии принятия',
        'riskPage.green.c1': 'Чёткий источник средств с подтверждающей документацией',
        'riskPage.green.c2': 'Легитимная бизнес-деятельность с верифицируемой историей',
        'riskPage.green.c3': 'Отсутствие санкционной экспозиции или PEP-статуса, либо полностью задокументированный PEP',
        'riskPage.green.c4': 'Реалистичные ожидания по срокам и банковским результатам',
        'riskPage.green.c5': 'Готовность соблюдать KYC/AML требования',
        'riskPage.yellow.label': 'ЖЁЛТЫЙ — БЕРЁМ С УСЛОВИЯМИ',
        'riskPage.yellow.title': 'Усиленная проверка',
        'riskPage.yellow.intro': 'Повышенная сложность, выше риск или нестандартная структура. Мы можем продолжить, но с дополнительными контролями и отдельным ценообразованием.',
        'riskPage.yellow.criteria': 'Что вызывает «жёлтый»',
        'riskPage.yellow.c1': 'Сложные мультиюрисдикционные структуры',
        'riskPage.yellow.c2': 'Отрасли с повышенным банковским вниманием (финтех, крипто-смежные, сырьевые)',
        'riskPage.yellow.c3': 'Задокументированный PEP-статус, требующий усиленных контролей',
        'riskPage.yellow.c4': 'Большие объёмы транзакций, требующие обоснования для комплаенса',
        'riskPage.yellow.conditions': 'Условия',
        'riskPage.yellow.cond1': 'Фиксированный объём с письменными границами',
        'riskPage.yellow.cond2': 'Отдельное ценообразование, отражающее дополнительную комплаенс-работу',
        'riskPage.yellow.cond3': 'Письменное подтверждение рисков от партнёра и клиента',
        'riskPage.yellow.cond4': 'Усиленный мониторинг на протяжении всего engagement',
        'riskPage.red.label': 'КРАСНЫЙ — ОТКАЗЫВАЕМ',
        'riskPage.red.title': 'Безусловный отказ',
        'riskPage.red.intro': 'Мы уходим. Без исключений, без переговоров. Защита наших банковских связей и репутации партнёра важнее любого отдельного кейса.',
        'riskPage.red.criteria': 'Автоматический отказ',
        'riskPage.red.c1': 'Санкционные физические или юридические лица',
        'riskPage.red.c2': 'Отсутствующая или сфабрикованная документация по источнику средств',
        'riskPage.red.c3': 'Позиция «сделайте без вопросов» к комплаенсу',
        'riskPage.red.c4': 'Высокорисковые отрасли: нелицензированные криптобиржи, офшорный гемблинг, оборонная торговля, сети shell-компаний',
        'riskPage.red.c5': 'Давление на обход регуляторных требований или банковских политик',
        'riskPage.red.c6': 'Намерение сокрытия без легальной структуры',

        // Partners Page
        'partnersPage.back': '← Назад к обзору',
        'partnersPage.label': 'ДЛЯ ПАРТНЁРОВ',
        'partnersPage.title': 'Создано для партнёров, которые ценят контроль.',
        'partnersPage.subtitle': 'Мы не конкурируем с вами. Мы не обходим вас. Мы исполняем то, что вы приносите — на ваших условиях.',
        'partnersPage.who.label': 'С КЕМ МЫ РАБОТАЕМ',
        'partnersPage.who.title': 'Профиль нашего партнёра',
        'partnersPage.who1.title': 'Wealth Managers и Family Offices',
        'partnersPage.who1.desc': 'Клиенты, переводящие капитал и семью в ОАЭ. Нужны банкинг, структуры и визы — от того, кто понимает комплаенс.',
        'partnersPage.who2.title': 'Иммиграционные консультанты',
        'partnersPage.who2.desc': 'Ведут планирование резидентства, но нуждаются в доверенном операторе на земле для регистрации, банкинга и комплаенса.',
        'partnersPage.who3.title': 'Налоговые консультанты и бухгалтеры',
        'partnersPage.who3.desc': 'Планируют налоговую структуру из домашней юрисдикции. Нужно исполнение в ОАЭ, которое дополняет консультацию, а не противоречит ей.',
        'partnersPage.who4.title': 'Юридические фирмы и бутиковые практики',
        'partnersPage.who4.desc': 'Консультируют по корпоративному структурированию и релокации. Нужно надёжное white-label исполнение без репутационного риска.',
        'partnersPage.why.label': 'ПОЧЕМУ ВЫБИРАЮТ НАС',
        'partnersPage.own.title': 'Защита клиента',
        'partnersPage.own.desc': 'Мы никогда не обходим партнёра и не продаём напрямую мимо вас. Ваши клиентские отношения остаются вашими. Каждый клиент закреплён за вами в CRM — без переназначения без согласия.',
        'partnersPage.trans.title': 'Прозрачность',
        'partnersPage.trans.desc': 'Чёткие статусы на каждом этапе. Контроль объёма и изменений задокументирован. Без скрытых сборов, без сюрпризных цен. Вы всегда знаете, где стоит кейс.',
        'partnersPage.ctrl.title': 'Контроль',
        'partnersPage.ctrl.desc': 'Решения принимаются заранее: можем ли мы продолжить и на каких именно условиях. Без обязательств без вашего ведома. Без изменений объёма без вашего согласия.',
        'partnersPage.qual.title': 'Качество',
        'partnersPage.qual.desc': 'Оптимизировано для банков и регуляторов, а не для «скорости любой ценой». Мы ставим на долгосрочную устойчивость. Структура, которая проходит комплаенс сегодня и выдерживает аудит завтра.',

        // CTA
        'cta.title': 'Начните с пилотного кейса',
        'cta.text': 'Получите вердикт pre-screen, коммерческое предложение с чёткими границами и план работы с контрольными точками.',
        'cta.kit': 'Запросить Partner Kit',
        'cta.case': 'Отправить кейс',

        // Partner Kit
        'partnerKit.back': 'Назад к обзору',
        'partnerKit.title': 'Partner Kit',
        'partnerKit.label': 'ПАРТНЁРСКАЯ ДОКУМЕНТАЦИЯ',
        'partnerKit.subtitle': 'Всё, что нужно, чтобы понять, как мы работаем, оценить совместимость и представить WTP вашим клиентам.',
        'partnerKit.featured': 'Обзор',
        'partnerKit.onepager.title': 'WTP One Pager',
        'partnerKit.onepager.desc': 'Краткий обзор нашей партнёрской модели, риск-фреймворка и продуктовой линейки. Идеально для передачи заинтересованным сторонам.',
        'partnerKit.download.btn': 'Скачать PDF',
        'partnerKit.docs': 'Документация',
        'partnerKit.docsSubtitle': 'Подробные документы для вас и ваших клиентов.',
        'partnerKit.process.title': 'Карта процесса',
        'partnerKit.process.desc': '10-этапный banking-first workflow. Что происходит после того, как вы направили клиента.',
        'partnerKit.risk.title': 'Риск-политика',
        'partnerKit.risk.desc': '3-уровневая классификация клиентов (Green / Yellow / Red). Кого направлять, а кого — нет.',
        'partnerKit.packages.title': 'Пакеты услуг',
        'partnerKit.packages.desc': 'L0–L3 — объём, ценовые диапазоны и что входит. Для передачи клиентам.',
        'partnerKit.intake.title': 'Чеклист приёма',
        'partnerKit.intake.desc': 'KYC Light — какие документы клиент должен подготовить до подачи кейса.',
        'partnerKit.cta.title': 'Готовы начать?',
        'partnerKit.cta.text': 'Отправьте первый кейс — мы проведём бесплатный pre-screen за 5-7 рабочих дней.',
        'partnerKit.cta.btn': 'Отправить кейс',
        'partnerKit.backHome': 'На главную',

        // Submit Case
        'submitCase.label': 'Партнёрский портал',
        'submitCase.title': 'Отправить кейс',
        'submitCase.subtitle': 'Начните процесс pre-screen. Пожалуйста, предоставьте следующую информацию о вашем клиенте.',
        'submitCase.contact': 'Контактная информация',
        'submitCase.name': 'Ваше имя',
        'submitCase.email': 'Email',
        'submitCase.telegram': 'Telegram',
        'submitCase.client': 'Данные клиента',
        'submitCase.nationality': 'Гражданство клиента',
        'submitCase.residency': 'Текущая резиденция',
        'submitCase.activity': 'Деятельность',
        'submitCase.activityPlaceholder': 'Опишите бизнес-деятельность клиента подробно...',
        'submitCase.banking': 'Банкинг и комплаенс',
        'submitCase.jurisdiction': 'Предпочтительная банковская юрисдикция',
        'submitCase.funds': 'Источник средств',
        'submitCase.fundsPlaceholder': 'Опишите происхождение средств подробно...',
        'submitCase.success': 'Ваш кейс успешно отправлен! Мы рассмотрим его и свяжемся с вами в течение 24 часов.',
        'submitCase.error': 'Что-то пошло не так. Попробуйте ещё раз или свяжитесь с нами напрямую.',
        'submitCase.submitting': 'Отправка...',
        'submitCase.submit': 'Отправить кейс',
        'submitCase.backHome': 'На главную',

        // Footer
        'footer.tagline': 'Execution-партнёр в ОАЭ.',
        'footer.contact': 'Контакты',
        'footer.legal': 'Юридическое',
        'footer.terms': 'Условия использования',
        'footer.privacy': 'Политика конфиденциальности',
        'footer.office': 'Офис',
        'footer.address': 'Office 1207, Arenco Tower\nMedia City, Дубай, ОАЭ',

        // Cookie Banner
        'cookie.text': 'Мы используем cookies для аналитики и улучшения сайта. Вы можете принять или отклонить необязательные cookies.',
        'cookie.learnMore': 'Подробнее',
        'cookie.accept': 'Принять все',
        'cookie.reject': 'Отклонить все',
        'cookie.ariaLabel': 'Согласие на cookies',

        // Form Consent
        'form.consent.prefix': 'Даю согласие на обработку персональных данных в соответствии с',
        'form.consent.link': 'Политикой конфиденциальности',

        // Accessibility
        'a11y.skipToContent': 'Перейти к содержимому',

        // Contact Page
        'contact.label': 'Связаться с нами',
        'contact.title': 'Контакты',
        'contact.subtitle': 'Свяжитесь с нашей командой. Мы ответим в течение 24 часов.',
        'contact.formTitle': 'Отправьте сообщение',
        'contact.name': 'Имя',
        'contact.namePlaceholder': 'Иван Иванов',
        'contact.email': 'Email',
        'contact.emailPlaceholder': 'ivan@example.com',
        'contact.telegram': 'Telegram',
        'contact.telegramPlaceholder': '@username',
        'contact.message': 'Сообщение',
        'contact.messagePlaceholder': 'Расскажите о вашем запросе...',
        'contact.success': 'Ваше сообщение отправлено! Мы свяжемся с вами в ближайшее время.',
        'contact.error': 'Что-то пошло не так. Попробуйте ещё раз или напишите нам на email.',
        'contact.submitting': 'Отправка...',
        'contact.submit': 'Отправить',
        'contact.backHome': 'На главную',
        'contact.info': 'Контакты',
        'contact.emailLabel': 'Email',
        'contact.phoneLabel': 'Телефон',
        'contact.officeLabel': 'Офис',
        'contact.address': 'Office 1207, Arenco Tower\nMedia City, Дубай, ОАЭ',
        'contact.responseTime': 'Время ответа',
        'contact.responseText': 'Обычно мы отвечаем в течение 24 часов в рабочие дни. По срочным вопросам свяжитесь через Telegram.',

        // Process Page UI
        'processPage.back': '\u2190 Назад к обзору',
        'processPage.notFound': 'Этап не найден',
        'processPage.notFoundText': 'Запрошенный этап процесса не существует.',
        'processPage.whatHappens': 'Что происходит',
        'processPage.actions': 'Действия',
        'processPage.result': 'Результат',
        'processPage.outcome': 'Итог',
        'processPage.nextStep': 'Следующий этап',
        'processPage.continue': 'Далее \u2192',

        // Terms Page
        'terms.back': '\u2190 Назад к процессу',
        'terms.title': 'Условия исполнения',
        'terms.label': 'ПРОЦЕСС ИСПОЛНЕНИЯ',
        'terms.subtitle': 'Наши принципы работы, риск-фреймворк и операционные правила для каждого engagement.',
        'terms.principles': 'Ключевые принципы',
        'terms.foundation': 'Основа',
        'terms.bankingFirst': 'Банк в приоритете',
        'terms.bankingFirstDesc': 'Мы оцениваем каждый кейс через призму банка до любой регистрации. Структура выбирается для банка, а не наоборот.',
        'terms.compliance': 'Комплаенс важнее скорости',
        'terms.complianceDesc': 'Мы не срезаем углы. Качество комплаенс-документации важнее скорости исполнения.',
        'terms.scope': 'Объём до обещаний',
        'terms.scopeDesc': 'Нет объёма \u2014 нет обещаний. Услуги, сроки и цены фиксируются до начала работ.',
        'terms.written': 'Только письменные изменения',
        'terms.writtenDesc': 'Все изменения объёма, дополнительные услуги и модификации должны быть подтверждены письменно.',
        'terms.riskTitle': 'Фреймворк оценки рисков',
        'terms.gatekeeping': 'Контроль допуска',
        'terms.accept': '\u2705 Берём в работу',
        'terms.accept1': 'Клиенты с потенциалом нескольких услуг',
        'terms.accept2': 'Партнёры и повторные клиенты',
        'terms.accept3': 'Прозрачная бизнес-логика',
        'terms.accept4': 'Долгосрочная ориентация',
        'terms.conditions': '\u26A0 Берём с условиями',
        'terms.conditions1': 'Сложные банковские кейсы',
        'terms.conditions2': 'Без гарантии результата',
        'terms.conditions3': 'Сложные структуры или юрисдикции',
        'terms.conditionsNote': '\u2192 Повышенная стоимость, фиксированный объём, без гарантии результата',
        'terms.decline': '\u274C Отказываем',
        'terms.decline1': 'Санкционные лица',
        'terms.decline2': 'Запросы «сделайте без документов»',
        'terms.decline3': 'Неготовность к предоплате',
        'terms.decline4': 'Разовые задачи без продолжения',
        'terms.decline5': 'Консьерж-запросы вне партнёрства',
        'terms.neverTitle': 'Чего мы никогда не делаем',
        'terms.redLines': 'Красные линии',
        'terms.never1': 'Обещать невозможные результаты',
        'terms.never2': 'Минимизировать или скрывать комплаенс-риски',
        'terms.never3': 'Импровизировать в серых зонах',
        'terms.never4': 'Обходить партнёра в коммуникации с клиентом',
        'terms.never5': 'Передавать данные клиента третьим лицам',
        'terms.never6': 'Заключать незадокументированные договорённости',

        // Updates Page
        'updates.back': '\u2190 Назад к обзору',
        'updates.title': 'Обновления',
        'updates.label': 'ЖУРНАЛ ИЗМЕНЕНИЙ',
        'updates.subtitle': 'Последние обновления по банковским сценариям, регуляторным изменениям и новым возможностям.',
        'updates.empty': 'Обновлений пока нет.',
        'updates.backHome': 'На главную',

        // Product Page UI
        'product.back': '\u2190 Назад к обзору',
        'product.notFound': 'Продукт не найден',
        'product.notFoundText': 'Запрошенная продуктовая линейка не существует.',
        'product.services': 'Услуги',
        'product.scope': 'Объём',
        'product.redFlags': 'Red Flags',
        'product.attention': 'Внимание',
        'product.result': 'Ожидаемый результат',
        'product.outcome': 'Итог',

        // SubmitCase Placeholders
        'submitCase.namePlaceholder': 'Иван Иванов',
        'submitCase.emailPlaceholder': 'ivan@example.com',
        'submitCase.telegramPlaceholder': '@username',
        'submitCase.nationalityPlaceholder': 'Выберите гражданство',
        'submitCase.residencyPlaceholder': 'Выберите резиденцию',
        'submitCase.jurisdictionPlaceholder': 'Выберите юрисдикцию',

        // Privacy Policy Page
        'privacy.back': '← На главную',
        'privacy.title': 'Политика конфиденциальности',
        'privacy.lastUpdated': 'Последнее обновление: 17 февраля 2026',
        'privacy.controller.title': '1. Контроллер данных',
        'privacy.controller.text': 'Контроллером данных является WELLCOME TO PARADISE REAL ESTATE BROKERS LLC, Office 1207, Arenco Tower, Media City, Dubai, UAE. По любым вопросам, касающимся ваших персональных данных, свяжитесь с нами: hello@wtpbrokers.com или +971 600 575-294.',
        'privacy.dataCollected.title': '2. Какие данные мы собираем',
        'privacy.dataCollected.formsIntro': 'Через наши формы мы можем собирать следующие персональные данные:',
        'privacy.dataCollected.name': 'Полное имя',
        'privacy.dataCollected.email': 'Адрес электронной почты',
        'privacy.dataCollected.telegram': 'Аккаунт Telegram',
        'privacy.dataCollected.nationality': 'Гражданство клиента',
        'privacy.dataCollected.residency': 'Текущее место проживания',
        'privacy.dataCollected.business': 'Описание бизнес-деятельности',
        'privacy.dataCollected.banking': 'Предпочтительная банковская юрисдикция',
        'privacy.dataCollected.funds': 'Описание источника средств',
        'privacy.dataCollected.autoIntro': 'С вашего согласия мы автоматически собираем:',
        'privacy.dataCollected.ip': 'IP-адрес (анонимизированный)',
        'privacy.dataCollected.browser': 'Тип и версия браузера',
        'privacy.dataCollected.pages': 'Посещённые страницы и данные о взаимодействии',
        'privacy.purpose.title': '3. Цели обработки',
        'privacy.purpose.crm': 'Обработка и управление клиентскими обращениями через CRM-систему',
        'privacy.purpose.communication': 'Связь с вами по вашему обращению',
        'privacy.purpose.analytics': 'Аналитика сайта для улучшения пользовательского опыта (с согласия)',
        'privacy.purpose.legal': 'Соблюдение правовых обязательств',
        'privacy.legalBasis.title': '4. Правовое основание',
        'privacy.legalBasis.consent': 'Согласие — для обработки форм и аналитических cookies (GDPR ст. 6(1)(a), UAE PDPL)',
        'privacy.legalBasis.contract': 'Исполнение договора — для обработки вашего кейса',
        'privacy.legalBasis.legitimate': 'Законный интерес — для безопасности и производительности сайта',
        'privacy.thirdParties.title': '5. Третьи стороны — обработчики данных',
        'privacy.thirdParties.bitrix': 'Bitrix24 — CRM-система для управления клиентскими обращениями',
        'privacy.thirdParties.google': 'Google Analytics 4 — аналитика сайта (только с вашего согласия)',
        'privacy.thirdParties.hosting': 'GitHub Pages — хостинг сайта',
        'privacy.thirdParties.note': 'Мы не продаём ваши персональные данные третьим лицам. Обработчики данных связаны соглашениями об обработке данных.',
        'privacy.retention.title': '6. Сроки хранения данных',
        'privacy.retention.text': 'Персональные данные, отправленные через формы, хранятся до 2 лет с момента вашего последнего взаимодействия с нами. Данные аналитики хранятся 14 месяцев. Вы можете запросить досрочное удаление в любое время.',
        'privacy.rights.title': '7. Ваши права',
        'privacy.rights.intro': 'Согласно GDPR, UAE PDPL и DIFC Data Protection Law, у вас есть следующие права:',
        'privacy.rights.access': 'Право доступа — получить копию своих персональных данных',
        'privacy.rights.rectification': 'Право на исправление — скорректировать неточные данные',
        'privacy.rights.erasure': 'Право на удаление — запросить удаление своих данных',
        'privacy.rights.restriction': 'Право на ограничение — ограничить обработку своих данных',
        'privacy.rights.portability': 'Право на переносимость данных — получить данные в структурированном формате',
        'privacy.rights.objection': 'Право на возражение — возразить против обработки на основании законного интереса',
        'privacy.rights.withdraw': 'Право на отзыв согласия — отозвать согласие в любое время без влияния на предшествующую обработку',
        'privacy.rights.contact': 'Для реализации любого из этих прав свяжитесь с нами: hello@wtpbrokers.com или +971 600 575-294. Мы ответим в течение 30 дней.',
        'privacy.cookies.title': '8. Cookies',
        'privacy.cookies.text': 'Мы используем cookies только с вашего явного согласия. Могут быть установлены следующие cookies:',
        'privacy.cookies.ga': '_ga, _ga_* — cookies Google Analytics для анализа использования сайта (категория: аналитика)',
        'privacy.cookies.session': 'wtp-cookie-consent — хранит ваш выбор по cookies (строго необходимый, согласие не требуется)',
        'privacy.cookies.control': 'Вы можете управлять настройками cookies в любое время, очистив cookies браузера и посетив сайт заново. Баннер согласия на cookies появится снова.',
        'privacy.changes.title': '9. Изменения в политике',
        'privacy.changes.text': 'Мы можем обновлять эту Политику конфиденциальности время от времени. Дата «последнего обновления» вверху отражает последнюю ревизию. Рекомендуем периодически просматривать эту страницу.',
        'privacy.contact.title': '10. Связаться с нами',
        'privacy.contact.text': 'Если у вас есть вопросы по этой Политике конфиденциальности или вы хотите реализовать свои права, свяжитесь с нами: hello@wtpbrokers.com, +971 600 575-294 или посетите wtpbrokers.com.',
    }
}
