// Regenerate public/sitemap.xml with EN + RU (/ru) entries and hreflang alternates.
// The EN path list is derived from the existing sitemap (idempotent: pre-existing /ru rows are
// dropped and rebuilt), so adding/removing an EN route stays a one-line edit to the EN block.
// prerender.mjs reads every <loc> and snapshots it, so RU routes are prerendered automatically.
//
// Usage: node scripts/gen-sitemap.mjs   (safe to run before each deploy)
import { readFileSync, writeFileSync } from "fs";
import { join, dirname } from "path";
import { fileURLToPath } from "url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const file = join(root, "public/sitemap.xml");
const SITE = "https://wtp.ae";

const src = readFileSync(file, "utf8");
// EN paths = every <loc> that isn't already a /ru mirror.
const enPaths = [...src.matchAll(/<loc>https:\/\/wtp\.ae([^<]*)<\/loc>/g)]
  .map((m) => m[1] || "/")
  .filter((p) => p !== "/ru" && !p.startsWith("/ru/"));

const ru = (p) => (p === "/" ? "/ru" : "/ru" + p);

// One <url> block with the full en/ru/x-default alternate cluster (same cluster on both variants).
function urlBlock(selfPath, enPath) {
  const enUrl = SITE + enPath;
  const ruUrl = SITE + ru(enPath);
  return [
    `  <url>`,
    `    <loc>${SITE + selfPath}</loc>`,
    `    <xhtml:link rel="alternate" hreflang="en" href="${enUrl}"/>`,
    `    <xhtml:link rel="alternate" hreflang="ru" href="${ruUrl}"/>`,
    `    <xhtml:link rel="alternate" hreflang="x-default" href="${enUrl}"/>`,
    `  </url>`,
  ].join("\n");
}

const blocks = [];
for (const p of enPaths) {
  blocks.push(urlBlock(p, p)); // EN
  blocks.push(urlBlock(ru(p), p)); // RU mirror
}

const xml = [
  `<?xml version="1.0" encoding="UTF-8"?>`,
  `<!-- Generated by scripts/gen-sitemap.mjs — EN + RU (/ru) with hreflang alternates. Edit EN routes here or regenerate. -->`,
  `<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9" xmlns:xhtml="http://www.w3.org/1999/xhtml">`,
  ...blocks,
  `</urlset>`,
  ``,
].join("\n");

writeFileSync(file, xml);
console.log(`sitemap.xml: ${enPaths.length} EN + ${enPaths.length} RU = ${enPaths.length * 2} urls`);
